//
//  SearchInteractor.swift
//  AppleMusic
//
//  Created Vitaly on 24.11.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchInteractor: SearchInteractorInput {
    
    // MARK: - Properties
    weak var presenter: SearchInteractorOutput?
    
    // MARK: - SearchInteractorInput -
    
    func fetchSearchingData(searchText: String) {
        SearchingManager.searchSongs(searchingText: searchText)
                .done {[weak self] (searchList) in
                    self?.presenter?.fetchedSearchList(lists: searchList)
                }.catch {[weak self] (error) in
                    self?.presenter?.fetchedSearchList(error: error)
                }
                .finally {[weak self] in
                    self?.presenter?.fetchedFully()
            }
    }

}
