//
//  SearchRouter.swift
//  AppleMusic
//
//  Created Vitaly on 24.11.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - SearchWireframeInterface -
extension SearchRouter: SearchWireframeInterface {
    
    func navigate(to option: SearchNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
