//
//  SearchInteractor.swift
//  AppleMusic
//
//  Created Vitaly on 24.11.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import RealmSwift

class SearchInteractor: SearchInteractorInput {
    
    // MARK: - Properties
    weak var presenter: SearchInteractorOutput?
    
    // MARK: - SearchInteractorInput -
    
    func fetchSearchingData(searchText: String) {
        SearchingManager.searchSongs(searchingText: searchText)
         .done {[weak self] (searchList) in
                self?.presenter?.fetchedSearchList(lists: searchList)
        }.catch {[weak self] (error) in
            self?.presenter?.fetchedSearchList(error: error)
        }
        .finally {[weak self] in
            self?.presenter?.fetchedFully()
        }
    }
    
    func saveTrackIntoDatabase(song: SearchCell.ViewModel) {
        let songRealm = TrackModel()
        guard
            let trackName = song.trackName,
            let artistName = song.artistName,
            let collectionName = song.collectionName,
            let songIconUrl = song.songIconUrl,
            let songmp4 = song.songMp4
            else { return }
        
        songRealm.trackID = DBManager.sharedInstance.getDataFromTrackList().count
        songRealm.trackName = trackName
        songRealm.artistName = artistName
        songRealm.collectionName = collectionName
        songRealm.songIconUrl100 = songIconUrl
        songRealm.songm4p = songmp4
        DBManager.sharedInstance.addDataTrackList(object: songRealm)
        self.presenter?.tracksWasSavedSuccesfully()
    }
    
}
