//
//  SearchViewController.swift
//  AppleMusic
//
//  Created Vitaly on 24.11.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import TableKit
import Lottie
import Motion

class SearchViewController: UIViewController {
    
    // MARK: - Properties
    var presenter: SearchPresenterInterface?
    private var tableDirector: TableDirector!
    private let searchController = UISearchController(searchResultsController: nil)
    private var timer: Timer?
    private let emptyView = LottieView()
    
    
    // MARK: - IBOutlets
    @IBOutlet weak var tableView: UITableView! {
        didSet {
            tableDirector = TableDirector(tableView: tableView)
        }
    }
    
    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        presenter?.viewDidLoad()
    }
    
}

// MARK: - SearchView
extension SearchViewController: SearchView {
    func displayEmptyView(animationName: String, title: String, message: String) {
        self.view.insertSubview(self.emptyView, belowSubview: self.tableView)
        self.emptyView.fillSuperview()
        emptyView.update(title: title, subTitle: message, lottieName: animationName, animationViewContentMode: .scaleAspectFill)
        emptyView.animate(.fade(1))
        tableView.animate(.fade(0))
    }
    
    func displayFetchedSongs(songs: [SearchCell.Data]) {
        emptyView.animate(.fade(0))
        tableView.animate(.fade(1))
        tableDirector.clear()
        let section = TableSection()
        let rows = songs.map{TableRow<SearchCell>(item: $0, actions: [])}
        section.append(rows: rows)
        tableDirector += [section]
        tableDirector.reload()
    }
    
}

// MARK: - UI Configuration
extension SearchViewController {
    func configureUI() {
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.obscuresBackgroundDuringPresentation = false
        definesPresentationContext = true
        searchController.searchBar.delegate = self
        view.backgroundColor = .background
        tableView.backgroundColor = .background
        tableView.separatorColor = .separatorColor
        tableView.tableFooterView = UIView()
    }
}

extension SearchViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { (_) in
            if !searchText.isEmpty {
                self.presenter?.fetchData(searchText: searchText)
            }
        })
    }
}
