//
//  SearchPresenter.swift
//  AppleMusic
//
//  Created Vitaly on 24.11.2019.
//  Copyright © 2019 Vitaly. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchPresenter {
    // MARK: - Properties
    weak private var view: SearchView?
    var interactor: SearchInteractorInput?
    private let router: SearchWireframeInterface

    // MARK: - Initialization and deinitialization -
    init(interface: SearchView, interactor: SearchInteractorInput?, router: SearchWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - SearchPresenterInterface -
extension SearchPresenter: SearchPresenterInterface {
    func fetchData(searchText: String) {
        self.interactor?.fetchSearchingData(searchText: searchText)
    }
}

// MARK: - SearchInteractorOutput -
extension SearchPresenter: SearchInteractorOutput {
    func fetchedSearchList(error: Error) {
        view?.displayEmptyView(animationName: "empty", title: "Ничего не найдено", message: "Пожалуйста, попробуйте снова")
    }
    
    func fetchedFully() {
        
    }
    
    func fetchedSearchList(lists: [Songs]) {
        print (lists.map({$0.songm4p}))
        guard lists.count > 0 else {
            view?.displayEmptyView(animationName: "NoConnection", title: "Ничего не найдено", message: "Пожалуйста, попробуйте снова")
            return
        }
        let rows = lists.map{SearchCell.Data(trackName: $0.trackName, artistName: $0.artistName, collectionName: $0.collectionName, songIconUrl: $0.artworkUrl100)}
        self.view?.displayFetchedSongs(songs: rows)
    }
}

